env:
  global:
  - secure: "av7eQ6L/TybtjAnhrtGVR9ja6dZMLLSHK8fljuzl4MdYv4/OI0ftTXm2o6JZNQ6jfwoWu3kRQCcrWYXLEPvWB4qaAcjyd9Wohm/1U1zcgOK6Gb3zIohKkDW0Vc5ciZp8joDrVMKGNgh49IPElRUYUIZAC/uWKYAcKZQhzo0UM5v1zIOBrL/WoRZ2KaOwva+vPbIlUOSwe7k0mg4aJghD7YqJwmb81H/TW2wP2xvksnnF5fKW8ODGCpRK0flgftxVx1tZyIVgGfe4ach2PLKaZa0F24ifyRBdPNAeCXGsC/9EcPePlJXuVVb91jmdUhq9Zcc1NZOqOGhvGUKKkvcizG0JgCgu9/DgahxKLiu2h20a+mvKGATZm2Q8FF4YjHpNMyeF3eUyTwrjIdS7+/7XD6igg/zD/i9jaXPwQEFvgYWCuAsqcAXQHPAUM41w3ifqmDlJhwmPIXsdf+OlPCvlhEiZBZWXmZjK96EMFRtdsdbt2RcC2jHXLeu8eCrAkoebyi/jXO7e+w9K+40U1eszH3diBSz7uCJvsyL0m0mZ1cq88nCjDl/yDeBiuCp+1MzlK0axeLj/YxUvgAEQnhGUEXm/Iyc6Z0JJaBS5SxCKMTEL9R7ApPtoqGdW88OWFVanEvNTJK+MhzUcMJuOqaSNY2mDkYQW5/njjNrWjFCFk64="
  - GIT_NAME: Travis CI
  - GIT_EMAIL: builds@travis-ci.org
  - TRAVIS_REPO_SLUG: spirillen/rpz-block-list
  - GIT_BRANCH: master
  - TZ: Europe/Copenhagen
  - PYFUNCEBLE_AUTO_CONFIGURATION: PyFunceble

os:
  - linux
  - osx

before_install:
  - sudo apt-get install -y wget curl

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix
      - libc6-dev

install:
  - pip3 install --upgrade pip
  - pip3 install PyFunceble ultimate-hosts-blacklist-whitelist

script:

  - bash .dev-tools/pre-deploy.sh


notifications:
  irc:
    channels:
      - "chat.oftc.net#mypdns"
    on_success: change # default: always
    on_failure: always # default: always
  email: false
